export const ADD_LYRIC = "ADD_LYRIC";
export const ADD_LYRIC_SUCCESS = "ADD_LYRIC_SUCCESS";

export const ALL_LYRICS = "ALL_LYRICS";
export const ALL_LYRICS_SUCCESS = "ALL_LYRICS_SUCCESS";

export const DELETE_LYRIC = "DELETE_LYRIC";
export const DELETE_LYRIC_SUCCESS = "DELETE_LYRIC_SUCCESS";
